version: '3.6'

services:
    create-react-app:
        build:
            target: prod
        ports:
            - '3000:3000'

    gatsby:
        build:
            target: prod
        ports:
            - '8000:8000'
