version: 2.1

defaults: &defaults
    docker:
        - image: circleci/node:10

master: &master
    filters:
        branches:
            only: master

orbs:
    cypress: cypress-io/cypress@1
jobs:
    alias:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run: yarn now alias
    install:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn --frozen-lockfile
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - persist_to_workspace:
                  root: .
                  paths:
                      - .
    build:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - setup_remote_docker:
                  docker_layer_caching: true
            - run: echo "SKIP_PREFLIGHT_CHECK=true" > ./projects/create-react-app/.env
            - run: yarn build
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run: yarn now
    lint:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run: yarn lint
    release:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - checkout
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: git config --global user.email "andrew@grexa.me"
            - run: git config --global user.name "Grex"
            - run: yarn release
    test:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run:
                  command: yarn test --ci --reporters=default --reporters=jest-junit --no-cache
                  environment:
                      JEST_JUNIT_OUTPUT: 'reports/jest/results.xml'
            - store_test_results:
                  path: reports
    test:integration:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run: yarn cypress install
            - run: yarn cypress run --record
            - cypress/run:
                  #   requires:
                  #       - cypress/install
                  record: true # record results on Cypress Dashboard
                  parallel: true # split all specs across machines
                  #   parallelism: 4 # use 4 CircleCI machines to finish quickly
                  group: 'all tests' # name this group "all tests" on the dashboard
                  #   start: 'npm start' # start server before running tests

workflows:
    version: 2
    build:
        jobs:
            # - build:
            #       requires:
            #           - install
            - alias:
                  <<: *master
                  requires:
                      - deploy
                      - release
            - deploy:
                  requires:
                      - install
            - install
            - lint:
                  requires:
                      - install
            - release:
                  <<: *master
                  requires:
                      #   - build
                      - install
                      - lint
                      - test
                      - test:integration
            - test:
                  requires:
                      - install
            - test:integration:
                  requires:
                      - install
