version: 2

defaults: &defaults
    docker:
        - image: circleci/node:10

jobs:
    install:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run: yarn --frozen-lockfile
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run: pwd; ls
            - persist_to_workspace:
                  root: workspace
                  paths:
                      - .
    build:
        <<: *defaults
        steps:
            - setup_remote_docker:
                  docker_layer_caching: true
            - run: yarn build
    deploy:
        <<: *defaults
        steps:
            - run: echo hello
    lint:
        <<: *defaults
        steps:
            - run: yarn lint
    release:
        <<: *defaults
        steps:
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: git config --global user.email "andrew@grexa.me"
            - run: git config --global user.name "Grex"
            - run: yarn release
    test:
        <<: *defaults
        steps:
            - run:
                  command: yarn test --ci --reporters=default --reporters=jest-junit --no-cache
                  environment:
                      JEST_JUNIT_OUTPUT: 'reports/jest/results.xml'
            - store_test_results:
                  path: reports
workflows:
    version: 2
    build:
        jobs:
            - build:
                  requires:
                      - install
            - deploy:
                  filters:
                      branches:
                          only: master
            - install
            - lint:
                  requires:
                      - install
            - release:
                  filters:
                      branches:
                          only: master
                  requires:
                      - build
                      - lint
                      - test
            - test:
                  requires:
                      - install
