version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: yarn lint
    test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: yarn test
workflows:
    version: 2
    build_and_test:
        jobs:
            - lint
            - test
