version: 2.1

defaults: &defaults
    executor: grxy/node

master: &master
    filters:
        branches:
            only: master

orbs:
    cypress: cypress-io/cypress@1
    grxy:
        commands:
            install:
                steps:
                    - attach_workspace:
                          at: ~/
                    - checkout
                    - restore_cache:
                          keys:
                              - cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - run: pwd; ls; echo; cd ~; pwd; ls; yarn cache dir; cd ~/.cache; pwd; ls
                    - run: yarn --frozen-lockfile
                    - run: yarn cypress install
                    - run: pwd; ls; echo; cd ~; pwd; ls; yarn cache dir; cd ~/.cache; pwd; ls
                    - save_cache:
                          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
                          paths:
                              - ~/.cache
                    - persist_to_workspace:
                          root: ~/
                          paths:
                              - project
                              - .cache/Cypress
        executors:
            node:
                docker:
                    - image: circleci/node:12-browsers
                environment:
                    - CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

jobs:
    alias:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn --silent now alias --token=$NOW_TOKEN
    build:
        <<: *defaults
        steps:
            - grxy/install
            - setup_remote_docker:
                  docker_layer_caching: true
            - run: echo "SKIP_PREFLIGHT_CHECK=true" > ./projects/create-react-app/.env
            - run: yarn build
    danger:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn danger ci
    deploy:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn --silent now --token=$NOW_TOKEN
            - run: yarn --silent now --token=$NOW_TOKEN alias grxy-$CIRCLE_SHA1.now.sh
    install:
        <<: *defaults
        steps:
            - grxy/install
    lint:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn lint
    release:
        <<: *defaults
        steps:
            - grxy/install
            - checkout
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: git config --global user.email "andrew@grexa.me"
            - run: git config --global user.name "Grex"
            - run: yarn release
    test:
        <<: *defaults
        steps:
            - grxy/install
            - run:
                  command: yarn test --ci --reporters=default --reporters=jest-junit --no-cache
                  environment:
                      JEST_JUNIT_OUTPUT: 'reports/jest/results.xml'
            - store_test_results:
                  path: reports
    # test-integration:
    #     docker:
    #         - image: cypress/browsers:chrome67-ff57
    #     steps:
    #         - grxy/install
    #         - run: yarn cypress install
    #         - run: CYPRESS_baseUrl=https://grxy-$CIRCLE_SHA1.now.sh yarn cypress run

workflows:
    version: 2
    build:
        jobs:
            # - alias:
            #       <<: *master
            #       requires:
            #           - deploy
            #           - release
            # - build
            - cypress/run:
                  build: 'yarn workspace @grxy/next build'
                  cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  command: 'CYPRESS_baseUrl=http://localhost:3000 yarn cypress run'
                  executor: grxy/node
                  install-command: 'yarn --frozen-lockfile'
                  post-install:
                      - run: pwd; ls; echo; cd ~; pwd; ls; yarn cache dir; cd ~/.cache; pwd; ls
                      - run: 'yarn cypress install'
                      - run: pwd; ls; echo; cd ~; pwd; ls; yarn cache dir; cd ~/.cache; pwd; ls
                  #   requires:
                  #       - install
                  start: 'yarn workspace @grxy/next start'
                  verify-command: 'yarn cypress verify'
                  wait-on: 'http://localhost:3000'
                  yarn: true
            - danger:
                  requires:
                      - install
            # - deploy
            - install
            - lint:
                  requires:
                      - install
            - release:
                  <<: *master
                  requires:
                      #   - build
                      - lint
                      - test
                      #   - test-integration
            - test:
                  requires:
                      - install
            # - test-integration:
            #       requires:
            #           - deploy
