version: 2.1

defaults: &defaults
    executor: grxy/node

master: &master
    filters:
        branches:
            only: master

orbs:
    grxy:
        commands:
            install:
                steps:
                    - checkout
                    - restore_cache:
                          keys:
                              - cache-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - run: yarn --frozen-lockfile
                    - run: yarn cypress install
                    - save_cache:
                          key: cache2-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
                          paths:
                              - ~/.cache
        executors:
            node:
                docker:
                    - image: circleci/node:12-browsers

jobs:
    alias:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn --silent now alias --token=$NOW_TOKEN
    danger:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn danger ci
    deploy:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn --silent now --token=$NOW_TOKEN
            - run: yarn --silent now --token=$NOW_TOKEN alias grxy-$CIRCLE_SHA1.now.sh
    install:
        <<: *defaults
        steps:
            - grxy/install
    lint:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn lint
    release:
        <<: *defaults
        steps:
            - grxy/install
            - checkout
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: git config --global user.email "andrew@grexa.me"
            - run: git config --global user.name "Grex"
            - run: yarn release
    test:
        <<: *defaults
        steps:
            - grxy/install
            - run:
                  command: yarn test --ci --reporters=default --reporters=jest-junit --no-cache
                  environment:
                      JEST_JUNIT_OUTPUT: 'reports/jest/results.xml'
            - store_test_results:
                  path: reports
    test-integration:
        <<: *defaults
        steps:
            - grxy/install
            - run: yarn workspace @grxy/next build
            - run:
                  command: yarn workspace @grxy/next start
                  background: true
            - run: npx wait-on http://localhost:3000
            - run: CYPRESS_baseUrl=http://localhost:3000 yarn cypress run

workflows:
    version: 2
    build:
        jobs:
            # - alias:
            #       <<: *master
            #       requires:
            #           - deploy
            #           - release
            - danger
            # - deploy
            - install
            - lint
            - release:
                  <<: *master
                  requires:
                      - lint
                      - test
                      - test-integration
            - test
            - test-integration
