version: 2
jobs:
    deploy:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: now alias --token $NOW_TOKEN
    lint:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: yarn lint
    test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: yarn test
workflows:
    version: 2
    build:
        jobs:
            - deploy:
                  filters:
                      branches:
                          only: master
            - lint
            - test
