version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run: yarn --frozen-lockfile
            - run: yarn build
    deploy:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn --frozen-lockfile
    lint:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn --frozen-lockfile
            - run: yarn lint
    release:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn --frozen-lockfile
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: git config --global user.email "andrew@grexa.me"
            - run: git config --global user.name "Grex"
            - run: yarn release
    test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn --frozen-lockfile
            - run: yarn test
workflows:
    version: 2
    build:
        jobs:
            - build
            - deploy:
                  filters:
                      branches:
                          only: master
            - lint
            - release:
                  filters:
                      branches:
                          only: master
                  requires:
                      - build
                      - lint
                      - test
            - test
