version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run: yarn
            - run: yarn build
    deploy:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            # - run: yarn now alias --token $NOW_TOKEN
    lint:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: yarn lint
    release:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: yarn release
    test:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - run: yarn
            - run: yarn test
workflows:
    version: 2
    build:
        jobs:
            - build
            - deploy:
                  filters:
                      branches:
                          only: master
            - lint
            - release
            - test
